export const KPI_MOCK_DELAY_MS = 400;

export const KPI_TARGETS = {
  ACCEPTANCE_RATE_MIN: 0.6,
  COMPLETION_RATE_MIN: 0.7,
  AVG_RESPONSE_TIME_MAX_MS: 180_000,
  EXPIRATION_RATE_MAX: 0.15,
} as const;

export const KPI_QUERY_STALE_TIME_MS = 60_000;
